version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports: 
      - 8888:8888 
    restart: on-failure
    volumes:
      - .:/usr/src/app
    depends_on:
      - forum-postgres # This service depends on postgres. Start that first.
      # - forum-mysql # This service depends on mysql. Start that first.
    environment:
      - DOMAIN_NAME=chodapi.com
    networks:
      - forum

  forum-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - forum

volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  forum:
    driver: bridge

